// GENERATED by scripts/gen-card-art-manifest.mjs — do not edit by hand.
// Maps a card id to its per-player image filename in public/cards/players/.
// Cards without an entry fall back to the shared position archetype art.
export const CARD_ART = new Map([
  ["wc26-10008043", "wc26-10008043.jpg"],
  ["wc26-10040792", "wc26-10040792.jpg"],
  ["wc26-10092510", "wc26-10092510.png"],
  ["wc26-10092845", "wc26-10092845.jpg"],
  ["wc26-10093982", "wc26-10093982.jpg"],
  ["wc26-10095772", "wc26-10095772.jpg"],
  ["wc26-10096036", "wc26-10096036.jpg"],
  ["wc26-10101818", "wc26-10101818.jpg"],
  ["wc26-10102608", "wc26-10102608.jpg"],
  ["wc26-1094267", "wc26-1094267.jpg"],
  ["wc26-312584", "wc26-312584.png"],
  ["wc26-453928", "wc26-453928.jpg"],
  ["wc26-463984", "wc26-463984.jpg"],
  ["wc26-464544", "wc26-464544.png"],
  ["wc26-46569", "wc26-46569.png"],
  ["wc26-49673", "wc26-49673.png"],
  ["wc26-755664", "wc26-755664.png"],
  ["wc26-889209", "wc26-889209.jpg"],
]);
