// GENERATED by scripts/gen-card-art-manifest.mjs — do not edit by hand.
// Maps a card id to its per-player image filename in public/cards/players/.
// Empty until you add images and re-run the manifest script; cards without an
// entry fall back to the shared position archetype art.
export const CARD_ART = new Map([]);
