[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
golazo = "GZUkNP4HhCdqZfZdQFhruArdz5oQ4Y8mgiS9wNPWc1ZL"
wager = "6qcrzBMCSNLeQK9y6xsMYEeNYMsKYbLmqbnNpkRZaogH"

[programs.devnet]
golazo = "GZUkNP4HhCdqZfZdQFhruArdz5oQ4Y8mgiS9wNPWc1ZL"
wager = "6qcrzBMCSNLeQK9y6xsMYEeNYMsKYbLmqbnNpkRZaogH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
